image: "openjdk:11"

before_script:
  - chmod +x mvnw

stages:
  - server-build

build:
  stage: server-build
  script: ./mvnw package
  artifacts:
    paths:
      - target/network-of-giving-0.0.1-SNAPSHOT.jar
