services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: NoG_database
  POSTGRES_USER: NoG_user
  POSTGRES_PASSWORD: NoG_password
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - server-build

build:
  image: "maven:3.6.3-jdk-11"
  stage: server-build
  script: 
    - cd ./server/network-of-giving
    - chmod +x mvnw
    - ./mvnw clean install -Dspring.datasource.url='jdbc:postgresql://postgres:5432/NoG_database'
