services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: NoG_database
  POSTGRES_USER: NoG_user
  POSTGRES_PASSWORD: NoG_password
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - build

server-build:
  image: "maven:3.6.3-jdk-11"
  stage: build
  script: 
    - cd ./server/network-of-giving
    - chmod +x mvnw
    - ./mvnw clean install -Dspring.datasource.url='jdbc:postgresql://postgres:5432/NoG_database'

client-build:
  image: trion/ng-cli
  stage: build
  before_script:
    - cd ./client/network-of-giving-client
    - npm ci
  script:
    - ng build --prod
  artifacts:
    expire_in: 1 day
    paths:
    - dist/